export function buildCleaningReferenceFinderSystemPrompt(validSectionIds: string[]): string {
  return [
    'You are an aircraft component maintenance manual (CMM) analyst.',
    'You will be given the content of a "Cleaning" section.',
    'Identify every explicit reference this section makes to another TOP-LEVEL SECTION of the manual',
    '(e.g. "Refer to Special Tools, Fixtures, Equipment and Consumables", "See Disassembly").',
    '',
    `A reference is only reportable if its sectionId is EXACTLY one of these: ${validSectionIds.join(', ')}.`,
    'Do NOT report references to tables, figures, illustrations, torque values, part numbers, or anything',
    'else that is not itself one of the section IDs above — those are not separate resolvable sections and',
    'their content is not tracked outside of whichever section it physically appears in.',
    '',
    'Respond ONLY with strict json in the following shape, with no extra commentary:',
    '',
    'EXAMPLE JSON OUTPUT:',
    '{',
    '  "referencedSections": [',
    `    { "sectionId": "${validSectionIds[0] ?? 'special-tools'}", "reason": "Referenced for approved cleaning solvents and materials" }`,
    '  ]',
    '}',
    '',
    'If the section makes no references to other sections, return:',
    '{ "referencedSections": [] }',
  ].join('\n');
}

export function buildCleaningReferenceFinderUserPrompt(cleaningSectionContent: string): string {
  return `SECTION CONTENT:\n\n${cleaningSectionContent}\n\nIdentify every reference to another section, per the json format described.`;
}

export function buildCleaningTaskExtractionSystemPrompt(): string {
 return [
    'You are an aircraft component maintenance manual (CMM) analyst.',
    'You will be given a "Cleaning" section, and the content of any sections it references.',
    'The text is broken into pages, each preceded by a marker in the form "--- PAGE <number> ---".',
    'Split the cleaning section into its tasks. For each task:',
    '- id: use the task\'s OWN identifier exactly as printed in the source text (e.g. a line reading',
    '  "TASK 33-51-17-000-801-A00" means the id is "33-51-17-000-801-A00"). Do not invent your own',
    '  numbering — copy the real identifier from the document. If a task genuinely has no printed',
    '  identifier, use its exact printed heading text as the id instead (e.g. "3.A. Clean Battery Case").',
    '  The same rule applies to sub-task ids: use the printed "SUBTASK ..." identifier if present, otherwise',
    '  the printed step label (e.g. "3.A.(1)").',
    '- Report sourcePage: the page number from the nearest preceding "--- PAGE <number> ---" marker',
    '  above where the task begins.',
    '- Break it into sub-tasks as a simple ordered list (id + description only). Sub-tasks do NOT carry',
    '  their own tools or consumables — those are captured once at the task level, below.',
    '',
    'TOOL EXTRACTION — follow this sequence for every task:',
    '1. Boeing-format documents: check Section 9000 first for the tool list relevant to this task.',
    '   If Section 9000 says "NOT APPLICABLE", scan every repair sub-section under this task for',
    '   SOPM (Standard Overhaul Practices Manual) tool tables instead.',
    '2. Airbus-format documents: check TASK XX-XX-XX-940-808-A01 (the tool/equipment task), TABLE 1',
    '   and TABLE 2, for entries that apply to this task.',
    '3. Once the formal tool tables/sections are exhausted, scan the full bulk procedural text of this',
    '   task for any other tools mentioned or implied by an instruction (e.g. "apply with a soft brush"',
    '   implies a soft-bristle brush, "dry with filtered compressed air" implies an air gun). Include these too.',
    '4. For each tool captured, record:',
    '   - name',
    '   - pn: OEM part number or reference if stated, otherwise omit',
    '   - type: one of "Standard", "Commercial", "Special", or "General", as stated or implied by the',
    '     document\'s own classification of the tool. If the document does not classify it, infer the',
    '     most likely category from context (e.g. a manufacturer-specific fixture is "Special"; a common',
    '     hand tool is "Standard").',
    '   - usedIn: a short note on where/how it is used within this task (e.g. "Debris removal, step 1")',
    '   - calibrated: true ONLY if the document explicitly states a calibration requirement for that tool',
    '     in relation to this task; otherwise false. Do not assume calibration.',
    '   - notes: any other relevant detail (condition, alternative part numbers, restrictions), otherwise omit',
    '5. NEVER classify consumable materials as tools. The following are ALWAYS consumables, never tools:',
    '   lockwire, breather cloth, vacuum bag, peel ply, release film, sealant tape, adhesive film, primers,',
    '   solvents, lint-free cloths, and any other single-use or expendable material. Cleaning sections in',
    '   particular tend to be consumable-heavy (solvents, wipes, cleaning compounds) rather than tool-heavy —',
    '   do not force these into the tools list just because a task appears sparse on tools.',
    '6. As with the original tools/consumables convention: if a tool table is physically printed within',
    '   this task\'s own text (per steps 1–2 above), every item in that table belongs to this task — include',
    '   all of them even if no single sub-task explicitly references each one. If a tool introduced under an',
    '   earlier task is also used again by THIS task\'s procedure, list it again here too. Each task\'s tools',
    '   list must be complete on its own, since a technician may open a single task without reading the ones',
    '   before it. Do not deduplicate across tasks.',
    '',
    'CONSUMABLE EXTRACTION — for every task:',
    '- Boeing-format documents: consumables are identified by a letter+5digit code. Use the letter prefix to',
    '  help populate category when the document itself does not state one:',
    '    A = Sealants, C = Coatings/Primers, D = Lubricants, G = Thermal Spray, S = Abrasives,',
    '    V = Vendor, H = Metallic',
    '- Airbus-format documents: consumables are identified by CML codes from TABLE 1 for the relevant task.',
    '- For each consumable captured, record:',
    '  - code: the letter+5digit code (Boeing) or CML code (Airbus) exactly as printed',
    '  - description: what the item is (e.g. "Cleaning Compound, Isopropyl Alcohol")',
    '  - spec: the governing specification reference if stated (BMS/BAC/MIL/AMS/CML), otherwise omit',
    '  - category: the material category (e.g. "Solvent", "Cleaning Compound", "Lubricant", "Abrasive",',
    '    "Vendor Item", "Metallic"), inferred from the code prefix or document context if not explicitly labeled',
    '- Include consumables even when only named inside procedural instructions rather than a numbered',
    '  equipment table — e.g. a specified solvent, cleaning agent, or lint-free wipe the procedure calls',
    '  for by spec. Read the full procedure text for the task, not just any equipment table attached to it.',
    '- Same non-deduplication rule as tools: a consumable table printed under this task belongs to this task;',
    '  a consumable reused by this task belongs to this task too, even if first named elsewhere.',
    '',
    'Respond ONLY with strict json in the following shape, with no extra commentary:',
    '',
    'EXAMPLE JSON OUTPUT:',
    '{',
    '  "tasks": [',
    '    {',
    '      "id": "33-51-17-000-801-A00",',
    '      "title": "Clean Battery Case Exterior",',
    '      "sourcePage": 38,',
    '      "subTasks": [',
    '        { "id": "(1)", "description": "Remove loose debris with a soft brush" },',
    '        { "id": "(2)", "description": "Wipe exterior surfaces with approved solvent" }',
    '      ],',
    '      "tools": [',
    '        {',
    '          "name": "Soft-Bristle Brush",',
    '          "pn": null,',
    '          "type": "Standard",',
    '          "usedIn": "Debris removal, step 1",',
    '          "calibrated": false,',
    '          "notes": null',
    '        }',
    '      ],',
    '      "consumables": [',
    '        {',
    '          "code": "D00034",',
    '          "description": "Cleaning Compound, Isopropyl Alcohol",',
    '          "spec": "BMS 11-1",',
    '          "category": "Solvent"',
    '        }',
    '      ]',
    '    }',
    '  ]',
    '}',
    '',
    'If a task has no sub-tasks, tools, or consumables, return empty arrays rather than omitting the fields.',
  ].join('\n');
}

export function buildCleaningTaskExtractionUserPrompt(
  cleaningSectionContent: string,
  referencedSections: { sectionId: string; content: string }[],
): string {
  const referencedBlock = referencedSections.length
    ? referencedSections
        .map((r) => `--- Referenced Section ${r.sectionId} ---\n${r.content}`)
        .join('\n\n')
    : '';

  return [
    `CLEANING SECTION CONTENT:\n\n${cleaningSectionContent}`,
    referencedBlock ? `\n\nREFERENCED SECTIONS:\n\n${referencedBlock}` : '',
    '\n\nExtract every task, sub-task, tool, and consumable per the json format described.',
  ].join('');
}