import {
  EXTERNAL_REFERENCE_EXTRACTION_INSTRUCTIONS,
  EXTERNAL_REFERENCE_JSON_EXAMPLE,
} from './common/externalReferenceInstructions';

export function buildInspectionReferenceFinderSystemPrompt(validSectionIds: string[]): string {
  return [
    'You are an aircraft component maintenance manual (CMM) analyst.',
    'You will be given the content of an "Inspection/Check" section.',
    'Identify every explicit reference this section makes to another TOP-LEVEL SECTION of the manual',
    '(e.g. "Refer to Disassembly", "See Special Tools, Fixtures, Equipment and Consumables").',
    '',
    `A reference is only reportable if its sectionId is EXACTLY one of these: ${validSectionIds.join(', ')}.`,
    'Do NOT report references to tables, figures, illustrations, torque values, part numbers, or anything',
    'else that is not itself one of the section IDs above — those are not separate resolvable sections and',
    'their content is not tracked outside of whichever section it physically appears in.',
    '',
    'Respond ONLY with strict json in the following shape, with no extra commentary:',
    '',
    'EXAMPLE JSON OUTPUT:',
    '{',
    '  "referencedSections": [',
    `    { "sectionId": "${validSectionIds[0] ?? 'disassembly'}", "reason": "Referenced for component removal sequence" }`,
    '  ]',
    '}',
    '',
    'If the section makes no references to other sections, return:',
    '{ "referencedSections": [] }',
  ].join('\n');
}

export function buildInspectionReferenceFinderUserPrompt(inspectionSectionContent: string): string {
  return `SECTION CONTENT:\n\n${inspectionSectionContent}\n\nIdentify every reference to another section, per the json format described.`;
}

export function buildInspectionTaskExtractionSystemPrompt(): string {
  return [
    'You are an aircraft component maintenance manual (CMM) analyst.',
    'You will be given an "Inspection/Check" section, and the content of any sections it references.',
    'The text is broken into pages, each preceded by a marker in the form "--- PAGE <number> ---".',
    'Split the inspection section into its tasks. For each task:',
    '- id: use the task\'s OWN identifier exactly as printed in the source text (e.g. a line reading',
    '  "TASK 33-51-17-200-801-A00" means the id is "33-51-17-200-801-A00"). Do not invent your own',
    '  numbering — copy the real identifier from the document. If a task genuinely has no printed',
    '  identifier, use its exact printed heading text as the id instead (e.g. "5.C. Visual Inspection").',
    '  The same rule applies to sub-task ids: use the printed "SUBTASK ..." identifier if present, otherwise',
    '  the printed step label (e.g. "5.C.(1)").',
    '- Report sourcePage: the page number from the nearest preceding "--- PAGE <number> ---" marker',
    '  above where the task begins.',
    '- Break it into sub-tasks as a simple ordered list (id + description only). Sub-tasks do NOT carry',
    '  their own tools or consumables — those are captured once at the task level, below.',
    '',
    'TOOL EXTRACTION — follow this sequence for every task:',
    '1. Boeing-format documents: check Section 9000 first for the tool list relevant to this task.',
    '   If Section 9000 says "NOT APPLICABLE", scan every repair sub-section under this task for',
    '   SOPM (Standard Overhaul Practices Manual) tool tables instead.',
    '2. Airbus-format documents: check TASK XX-XX-XX-940-808-A01 (the tool/equipment task), TABLE 1',
    '   and TABLE 2, for entries that apply to this task.',
    '3. Once the formal tool tables/sections are exhausted, scan the full bulk procedural text of this',
    '   task for any other tools mentioned or implied by an instruction (e.g. "check dimension" implies',
    '   calipers, "check for cracks" implies a magnifying glass or NDT equipment). Include these too.',
    '4. For each tool captured, record:',
    '   - name',
    '   - pn: OEM part number or reference if stated, otherwise omit',
    '   - type: one of "Standard", "Commercial", "Special", or "General", as stated or implied by the',
    '     document\'s own classification of the tool. If the document does not classify it, infer the',
    '     most likely category from context (e.g. a manufacturer-specific fixture is "Special"; a common',
    '     hand tool is "Standard").',
    '   - usedIn: a short note on where/how it is used within this task (e.g. "Dimensional check, step 2")',
    '   - calibrated: true ONLY if the document explicitly states a calibration requirement for that tool',
    '     in relation to this task; otherwise false. Do not assume calibration.',
    '   - notes: any other relevant detail (condition, alternative part numbers, restrictions), otherwise omit',
    '5. NEVER classify consumable materials as tools. The following are ALWAYS consumables, never tools:',
    '   breather cloth, vacuum bag, peel ply, release film, sealant tape, adhesive film, primers, solvents,',
    '   lint-free cloths, dye penetrant, developer, and any other single-use or expendable material.',
    '6. As with the original tools/consumables convention: if a tool table is physically printed within',
    '   this task\'s own text (per steps 1–2 above), every item in that table belongs to this task — include',
    '   all of them even if no single sub-task explicitly references each one. If a tool introduced under an',
    '   earlier task is also used again by THIS task\'s procedure, list it again here too. Each task\'s tools',
    '   list must be complete on its own, since a technician may open a single task without reading the ones',
    '   before it. Do not deduplicate across tasks.',
    '',
    'CONSUMABLE EXTRACTION — for every task:',
    '- Boeing-format documents: consumables are identified by a letter+5digit code. Use the letter prefix to',
    '  help populate category when the document itself does not state one:',
    '    A = Sealants, C = Coatings/Primers, D = Lubricants, G = Thermal Spray, S = Abrasives,',
    '    V = Vendor, H = Metallic',
    '- Airbus-format documents: consumables are identified by CML codes from TABLE 1 for the relevant task.',
    '- For each consumable captured, record:',
    '  - code: the letter+5digit code (Boeing) or CML code (Airbus) exactly as printed',
    '  - description: what the item is (e.g. "Dye Penetrant")',
    '  - spec: the governing specification reference if stated (BMS/BAC/MIL/AMS/CML), otherwise omit',
    '  - category: the material category (e.g. "Sealant", "Coating", "Lubricant", "Abrasive", "Vendor Item",',
    '    "Metallic"), inferred from the code prefix or document context if not explicitly labeled',
    '- Include consumables even when only named inside procedural instructions rather than a numbered',
    '  equipment table — e.g. a specified NDT medium, a cleaning solvent prior to visual inspection, or any',
    '  other material the procedure calls for by spec. Read the full procedure text, not just any attached',
    '  equipment table.',
    '- Same non-deduplication rule as tools: a consumable table printed under this task belongs to this task;',
    '  a consumable reused by this task belongs to this task too, even if first named elsewhere.',
    '',
    EXTERNAL_REFERENCE_EXTRACTION_INSTRUCTIONS,
    '',
    'Respond ONLY with strict json in the following shape, with no extra commentary:',
    '',
    'EXAMPLE JSON OUTPUT:',
    '{',
    '  "tasks": [',
    '    {',
    '      "id": "33-51-17-200-801-A00",',
    '      "title": "Dimensional Inspection",',
    '      "sourcePage": 74,',
    '      "subTasks": [',
    '        { "id": "(1)", "description": "Measure bore diameter at three points" },',
    '        { "id": "(2)", "description": "Compare against limits in Fits and Clearances" }',
    '      ],',
    '      "tools": [',
    '        {',
    '          "name": "Inside Micrometer",',
    '          "pn": null,',
    '          "type": "Standard",',
    '          "usedIn": "Dimensional inspection, steps 1-2",',
    '          "calibrated": true,',
    '          "notes": null',
    '        }',
    '      ],',
    '      "consumables": [',
    '        {',
    '          "code": "A00247",',
    '          "description": "Dye Penetrant",',
    '          "spec": "AMS 2644",',
    '          "category": "Vendor Item"',
    '        }',
    '      ],',
    EXTERNAL_REFERENCE_JSON_EXAMPLE,
    '    }',
    '  ]',
    '}',
    '',
    'If a task has no sub-tasks, tools, consumables, or external references, return empty arrays',
    'rather than omitting the fields.',
  ].join('\n');
}

export function buildInspectionTaskExtractionUserPrompt(
  inspectionSectionContent: string,
  referencedSections: { sectionId: string; content: string }[],
): string {
  const referencedBlock = referencedSections.length
    ? referencedSections
        .map((r) => `--- Referenced Section ${r.sectionId} ---\n${r.content}`)
        .join('\n\n')
    : '';

  return [
    `INSPECTION SECTION CONTENT:\n\n${inspectionSectionContent}`,
    referencedBlock ? `\n\nREFERENCED SECTIONS:\n\n${referencedBlock}` : '',
    '\n\nExtract every task, sub-task, tool, and consumable per the json format described.',
  ].join('');
}